version: '3.4'

services:
  thingsboard:
    container_name: thingsboard
    image: thingsboard/tb-postgres
    ports:
      - 9090:9090
      - 1883:1883
      - 5683:5683/udp
    restart: always
    depends_on:
      - postgresql
    environment:
      DATABASE_ENTITIES_TYPE: sql
      DATABASE_TS_TYPE: sql
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 5
      SQL_POSTGRES_TS_KV_PARTITIONING: MONTHS
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresPassword

  postgresql:
    container_name: postgresql
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_USER: postgres
      POSTGRES_DB: thingsboard
    ports:
      - 5432:5432
